"""add autores e categorias

Revision ID: a09e20d36ab9
Revises: 7deb4eaf030e
Create Date: 2026-06-14 17:59:41.435863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09e20d36ab9'
down_revision = '7deb4eaf030e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('partido', sa.String(length=20), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('id_externo', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('url_foto', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_externo')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.Column('icone', sa.String(length=50), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('proposicao_categoria',
    sa.Column('proposicao_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['proposicao_id'], ['proposicoes.id'], ),
    sa.PrimaryKeyConstraint('proposicao_id', 'categoria_id')
    )
    with op.batch_alter_table('proposicoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autor_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_proposicoes_ano', ['ano'], unique=False)
        batch_op.create_index('idx_proposicoes_categoria', ['categoria'], unique=False)
        batch_op.create_index('idx_proposicoes_data_apresentacao', ['data_apresentacao'], unique=False)
        batch_op.create_index('idx_proposicoes_descricao_situacao', ['descricao_situacao'], unique=False)
        batch_op.create_index('idx_proposicoes_partido_id', ['partido_id'], unique=False)
        batch_op.create_index('idx_proposicoes_sigla_tipo', ['sigla_tipo'], unique=False)
        batch_op.create_index('idx_proposicoes_tipo_ano', ['sigla_tipo', 'ano'], unique=False)
        batch_op.create_foreign_key(None, 'autores', ['autor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposicoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_proposicoes_tipo_ano')
        batch_op.drop_index('idx_proposicoes_sigla_tipo')
        batch_op.drop_index('idx_proposicoes_partido_id')
        batch_op.drop_index('idx_proposicoes_descricao_situacao')
        batch_op.drop_index('idx_proposicoes_data_apresentacao')
        batch_op.drop_index('idx_proposicoes_categoria')
        batch_op.drop_index('idx_proposicoes_ano')
        batch_op.drop_column('autor_id')

    op.drop_table('proposicao_categoria')
    op.drop_table('categorias')
    op.drop_table('autores')
    # ### end Alembic commands ###
