"""schema inicial com categorias N:N e check constraint

Revision ID: babbb73a5d52
Revises: 
Create Date: 2026-06-17 13:05:03.440057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'babbb73a5d52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.Column('icone', sa.String(length=50), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('requisicoes_api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('data_requisicao', sa.DateTime(), nullable=False),
    sa.Column('quantidade_registros', sa.Integer(), nullable=False),
    sa.Column('status_requisicao', sa.String(length=50), nullable=False),
    sa.Column('tempo_execucao_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('google_id', sa.String(length=100), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('historico_consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('termo_busca', sa.String(length=255), nullable=False),
    sa.Column('data_consulta', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla_tipo', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('ementa', sa.Text(), nullable=False),
    sa.Column('data_apresentacao', sa.Date(), nullable=False),
    sa.Column('descricao_situacao', sa.String(length=150), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=True),
    sa.Column('sigla_partido', sa.String(length=20), nullable=False),
    sa.Column('data_coleta', sa.DateTime(), nullable=False),
    sa.CheckConstraint("descricao_situacao IN ('Em tramitação', 'Aprovado', 'Arquivado', 'Encerrado')", name='ck_proposicao_status'),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla_tipo', 'numero', 'ano')
    )
    with op.batch_alter_table('proposicoes', schema=None) as batch_op:
        batch_op.create_index('idx_proposicoes_ano', ['ano'], unique=False)
        batch_op.create_index('idx_proposicoes_data_apresentacao', ['data_apresentacao'], unique=False)
        batch_op.create_index('idx_proposicoes_descricao_situacao', ['descricao_situacao'], unique=False)
        batch_op.create_index('idx_proposicoes_partido_id', ['partido_id'], unique=False)
        batch_op.create_index('idx_proposicoes_sigla_tipo', ['sigla_tipo'], unique=False)
        batch_op.create_index('idx_proposicoes_tipo_ano', ['sigla_tipo', 'ano'], unique=False)

    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('proposicao_id', sa.Integer(), nullable=False),
    sa.Column('data_favorito', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proposicao_id'], ['proposicoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'proposicao_id', name='uq_favorito_usuario_proposicao')
    )
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.create_index('idx_favoritos_usuario_proposicao', ['usuario_id', 'proposicao_id'], unique=False)

    op.create_table('proposicao_categoria',
    sa.Column('proposicao_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['proposicao_id'], ['proposicoes.id'], ),
    sa.PrimaryKeyConstraint('proposicao_id', 'categoria_id')
    )
    op.create_table('tramitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposicao_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('id_situacao', sa.Integer(), nullable=False),
    sa.Column('descricao_situacao', sa.String(length=150), nullable=False),
    sa.Column('descricao_tramitacao', sa.Text(), nullable=False),
    sa.Column('sigla_orgao', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['proposicao_id'], ['proposicoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tramitacoes')
    op.drop_table('proposicao_categoria')
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_index('idx_favoritos_usuario_proposicao')

    op.drop_table('favoritos')
    with op.batch_alter_table('proposicoes', schema=None) as batch_op:
        batch_op.drop_index('idx_proposicoes_tipo_ano')
        batch_op.drop_index('idx_proposicoes_sigla_tipo')
        batch_op.drop_index('idx_proposicoes_partido_id')
        batch_op.drop_index('idx_proposicoes_descricao_situacao')
        batch_op.drop_index('idx_proposicoes_data_apresentacao')
        batch_op.drop_index('idx_proposicoes_ano')

    op.drop_table('proposicoes')
    op.drop_table('historico_consultas')
    op.drop_table('usuarios')
    op.drop_table('requisicoes_api')
    op.drop_table('partidos')
    op.drop_table('categorias')
    # ### end Alembic commands ###
