"""add sync_executions and classificacao_status

Revision ID: ca57241159f9
Revises: babbb73a5d52
Create Date: 2026-06-26 19:46:12.533871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca57241159f9'
down_revision = 'babbb73a5d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_processados', sa.Integer(), nullable=False),
    sa.Column('total_inseridos', sa.Integer(), nullable=False),
    sa.Column('total_atualizados', sa.Integer(), nullable=False),
    sa.Column('total_erros', sa.Integer(), nullable=False),
    sa.Column('mensagem_erro', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposicoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classificacao_status', sa.String(length=30), nullable=False, server_default='pendente_classificacao'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposicoes', schema=None) as batch_op:
        batch_op.drop_column('classificacao_status')

    op.drop_table('sync_executions')
    # ### end Alembic commands ###
